[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "P3D"
version = "0.0.0"
dependencies = [
    "numpy>=2.0.0",
    "plotly>=6.0.0",
    "dash>=3.0.0"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]